tofinish/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'tofinish.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^grappelli/', include('grappelli.urls')),
    url(r'^index/', 'main.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'test_template/$', 'main.views.test_template'),
    url(r'login/$', 'main.views.login_form'),
    url(r'login/process/$', 'main.views.login_process'),
    url(r'logout/', 'main.views.logout_view'),
    url(r'^profile/(\d+)/$', 'main.views.users_profile'),

    url(r'task_project/$', 'task_project.views.index'),
 	url(r'task_project/add$', 'task_project.views.add'),
 	url(r'^task_project/(\d+)', 'task_project.views.detail'),
 	url(r'^task_project/delete/(\d+)', 'task_project.views.delete'),   
 	url(r'^task_project/edit/(\d+)', 'task_project.views.edit'),   
 	url(r'^task_project/edit_process$', 'task_project.views.edit_process'),   
 	url(r'^task_project/member/(\d+)', 'task_project.views.list_member'),
 	url(r'^task_project/groups/(\d+)', 'task_project.views.list_task_groups'),
 	url(r'^task_project/tasks/(\d+)', 'task_project.views.list_tasks'),
 	url(r'^task_project/groups/edit/(\d+)/(\d+)', 'tasks.views.edit_group'),   
 	url(r'^task_project/groups/delete/(\d+)', 'tasks.views.delete_group'),   
 	url(r'^task_project/groups/edit_process$', 'tasks.views.edit_group_process'),   
 	url(r'^task_project/groups/add/(\d+)', 'tasks.views.add_group'),
 	url(r'^task_project/groups/detail/(\d+)', 'tasks.views.detail_group'),
 	url(r'^task_project/invitation/$', 'task_project.views.invitation'),
    url(r'^task_project/invitation/before/$', 'task_project.views.invitation_before'),
    url(r'^task_project/invitation/approve/(\d+)', 'task_project.views.approve_invitation'),
    
 	url(r'^tasks/add/(\d+)', 'tasks.views.add'),
 	url(r'^tasks/edit/(\d+)', 'tasks.views.edit'),
 	url(r'^tasks/edit_process', 'tasks.views.edit_process'),
 	url(r'^tasks/delete/(\d+)', 'tasks.views.delete'),   
 	url(r'^tasks/(\d+)', 'tasks.views.detail'),
 	url(r'^tasks/mine', 'tasks.views.my_task'),
 	url(r'^tasks/discussion/add', 'tasks.views.add_discussion_process'),
    url(r'^tasks/discussion/delete/(\d+)', 'tasks.views.delete_discussion'),
    url(r'^tasks/attachment/add', 'tasks.views.add_attachment_process'),
    
    url(r'^flashcard/$', 'flashcard.views.index'),
 	url(r'^flashcard/add$', 'flashcard.views.add'),
 	url(r'^flashcard/delete/(\d+)', 'flashcard.views.delete'), 
 	url(r'^flashcard/edit/(\d+)', 'flashcard.views.edit'),   
 	url(r'^flashcard/edit_process$', 'flashcard.views.edit_process'),  

 	url(r'^api/users/all$', 'main.views.all_users'),   
 	url(r'^api/task_project_member/add/(\d+)/(\d+)', 'task_project.views.add_member'),   
 	url(r'^api/task_project_member/by_project/(\d+)', 'task_project.views.get_member_by_project'),   
 	url(r'^api/task_project_member/suggest/(\d+)', 'task_project.views.suggest_member_by_project'),   
 	url(r'^api/task_project_member/reject/', 'task_project.views.reject_member'), 
    url(r'^api/task_project_member/leave/', 'task_project.views.leave_member'),
    url(r'^api/task_project_member/reapprove/', 'task_project.views.reapprove_member'),
    url(r'^api/tasks/task_project/(\d+)', 'tasks.views.all_tasks_by_project'),
    url(r'^api/tasks/change/', 'tasks.views.change_task_status'),
    url(r'^api/tasks/attachment/delete/', 'tasks.views.delete_attachment_process'),
    url(r'^api/tasks/discussion/delete/', 'tasks.views.delete_discussion_process'),
    url(r'^api/flashcard/item/add/', 'flashcard.views.add_item'),   
	url(r'^api/flashcard/item/delete/', 'flashcard.views.delete_item'),   
		 										
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class FlashcardCategory(models.Model):
	name = models.CharField(max_length=100, default="unknown")
	description = models.TextField(blank=True, default="unknown")

	def __unicode__(self):
		return self.name
    
	class Meta:
		ordering = ['name']

class Flashcard(models.Model):
	name = models.CharField(max_length=100, default="unknown")
	description = models.TextField(blank=True, default="unknown")
	created_time = models.DateTimeField(auto_now=True)
	flashcard_category = models.ForeignKey(FlashcardCategory)
	owner = models.ForeignKey(User, default=1)
	
	def __unicode__(self):
		return "%s" % (self.name)
    
	class Meta:
		ordering = ['created_time']

class FlashcardItem(models.Model):
	name = models.CharField(max_length=100, default="unknown")
	description = models.TextField(blank=True, default="unknown")
	created_time = models.DateTimeField(auto_now=True)
	flashcard = models.ForeignKey(Flashcard)
	owner = models.ForeignKey(User, default=1)
	
	def __unicode__(self):
		return "%s" % (self.name)
    
	class Meta:
		ordering = ['created_time']

flashcard/forms.py
from django import forms
from flashcard.models import *

class FlashcardForm(forms.Form):

	name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control', 'rows': '4'}))
	flashcard_category = forms.ModelChoiceField(FlashcardCategory.objects.all(), widget=forms.Select(attrs={'class':'form-control'}))
	owner = forms.IntegerField(widget=forms.HiddenInput)

flashcard/views.py
from django.shortcuts import render_to_response, redirect
from django.http import HttpResponse
from django.core.context_processors import csrf
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.contrib.auth.models import User
from django.template import RequestContext

from flashcard.models import *
from flashcard.forms import *

import json

# Create your views here.
login_url = '/login/'

@login_required(login_url=login_url)
def index(request):
	flashcard = Flashcard.objects.all().filter(owner=request.user.id)
	c = {}
	c.update(csrf(request))
	c.update({ 'flashcard':flashcard })
	return render_to_response('flashcard/list.html', c, context_instance=RequestContext(request))

@login_required(login_url=login_url)
def add(request):
	if request.method == 'POST':
		form = FlashcardForm(request.POST)
		if form.is_valid():
			user = User.objects.get(id=int(request.POST['owner']))
			flashcard_category = FlashcardCategory.objects.get(id=int(request.POST['flashcard_category']))
			project = Flashcard(
				name = request.POST['name'],
				description = request.POST['description'],
				owner = user,
				flashcard_category = flashcard_category,
			)
			project.save()

			return redirect('/flashcard')
	else:
		form = FlashcardForm(initial={ 'owner':request.user.id })
	
	c = {}
	c.update(csrf(request))
	c.update({'form':form})
	return render_to_response('flashcard/add.html', c,  context_instance=RequestContext(request))

@login_required(login_url=login_url)
def delete(request, flashcard_id):
	flashcard = Flashcard.objects.get(id=int(flashcard_id))
	flashcard.delete()
	return redirect('/flashcard')	

@login_required(login_url=login_url)
def edit(request, flashcard_id):
	flashcard = Flashcard.objects.get(id=int(flashcard_id))
	form = FlashcardForm(
		initial= { 
			'name' : flashcard.name,
			'description' : flashcard.description,
			'flashcard_category' : flashcard.flashcard_category,
			'owner':flashcard.owner.id 
		}
	)
	c = {}
	c.update(csrf(request))
	c.update({'form':form, 'flashcard':flashcard })
	return render_to_response('flashcard/edit.html', c,  context_instance=RequestContext(request))

@login_required(login_url=login_url)
def edit_process(request):
	if request.method == 'POST':
		form = FlashcardForm(request.POST)
		if form.is_valid():
			user = User.objects.get(id=int(request.POST['owner']))
			flashcard_category = FlashcardCategory.objects.get(id=int(request.POST['flashcard_category']))
			flashcard = Flashcard.objects.get(id=int(request.POST['flashcard_id']))
			flashcard.name = request.POST['name']
			flashcard.description = request.POST['description']
			flashcard.owner = user
			flashcard.flashcard_category = flashcard_category
			flashcard.save()
			return redirect('/flashcard')
		else:
			return redirect('/flashcard/edit/'+request.POST['flashcard_id'])

@login_required(login_url=login_url)
def add_item(request):
	flashcard_id = request.POST['flashcard-item-flashcard']
	flashcard_item_name = request.POST['flashcard-item-name']

	user = User.objects.get(id=int(request.user.id))
	flashcard = Flashcard.objects.get(id=int(flashcard_id))
	flashcard_item = FlashcardItem(
		name = flashcard_item_name,
		description = "",
		owner = user,
		flashcard = flashcard,
	)

	flashcard_item.save()
	results = serializers.serialize("json", FlashcardItem.objects.all().filter(flashcard=flashcard))
	results = { 'msg':'flashcard item has been saved', 'error':200, 'results': results}
	
	resp = json.dumps(results)
	response = HttpResponse(resp, content_type="application/json")
	
	return response

@login_required(login_url=login_url)
def delete_item(request):
	flashcard_item_id = request.POST['flashcard-item-id']
	flashcard_item = FlashcardItem.objects.get(id=int(flashcard_item_id))
	
	flashcard_item_id = { 'flashcard_item_id': flashcard_item_id }

	if flashcard_item:
		flashcard_item.delete()
		results = { 'msg':'flashcard item has been deleted', 'error':200, 'results':flashcard_item_id }
	else:
		results = { 'msg':'fail to delete flashcard_item', 'error':201, 'resulst':flashcard_item_id }
	
	resp = json.dumps(results)
	response = HttpResponse(resp, content_type="application/json")
	
	return response

templates/flashcard/add.html
{% extends "main/layout.html" %}

{% block main_content %}
<div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/flashcard">Kartu Pengingat</a></li>
      <li class="active">Tambah Kartu Pengingat</li>
    </ol>
</div>
<div class="col-md-12">
    <span style="font-size:30px;font-weight:strong;">Kartu Pengingat</span>
    <br/>
    <br/>
</div>
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
          <form class="form-horizontal"action="/flashcard/add" method="post">
                {% csrf_token %}
                  <div class="form-group">
                    <label for="inputEmail1" class="col-lg-2 control-label">Nama</label>
                    <div class="col-lg-10">
                      <!-- <input class="form-control" id="inputEmail1" placeholder="Email" type="email"> -->
                        {{ form.name.errors }}
                        {{ form.name }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Deskripsi</label>
                    <div class="col-lg-10">
                      <!-- <input class="form-control" id="inputPassword1" placeholder="Password" type="password"> -->
                      {{ form.description.errors }}
                      {{ form.description }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Kategori Kartu Pengingat</label>
                    <div class="col-lg-10">
                        {{ form.flashcard_category.errors }}
                        {{ form.flashcard_category }}
                        {{ form.owner.errors }}
                        {{ form.owner }}
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                      <input type="submit" class="btn btn-info" value="Simpan" />
                    </div>
                  </div>
          </form>
      </div>
    </div>
</div>
{% endblock %}

templates/flashcard/edit.html
{% extends "main/layout.html" %}

{% block main_content %}
<div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/flashcard">Kartu Pengingat</a></li>
      <li class="active">Edit Kartu Pengingat</li>
    </ol>
</div>
<div class="col-md-12">
    <span style="font-size:30px;font-weight:strong;">Kartu Pengingat</span>
    <br/>
    <br/>
</div>
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
          <form class="form-horizontal"action="/flashcard/edit_process" method="post">
                {% csrf_token %}
                  <div class="form-group">
                    <label for="inputEmail1" class="col-lg-2 control-label">Nama</label>
                    <div class="col-lg-10">
                      <!-- <input class="form-control" id="inputEmail1" placeholder="Email" type="email"> -->
                        {{ form.name.errors }}
                        {{ form.name }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Deskripsi</label>
                    <div class="col-lg-10">
                      <!-- <input class="form-control" id="inputPassword1" placeholder="Password" type="password"> -->
                      {{ form.description.errors }}
                      {{ form.description }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Kategori Kartu Pengingat</label>
                    <div class="col-lg-10">
                        {{ form.flashcard_category.errors }}
                        {{ form.flashcard_category }}
                        {{ form.owner.errors }}
                        {{ form.owner }}
                        <input type="hidden" name="flashcard_id" value="{{ flashcard.id }}" />
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                      <input type="submit" class="btn btn-info" value="Simpan" />
                    </div>
                  </div>
            </form>
      </div>
    </div>
</div>
{% endblock %}

templates/flashcard/list.html
{% extends "main/layout.html" %}

{% block main_content %}
<div class="col-md-12">
    <ol class="breadcrumb">
      <li class="active">Kartu Pengingat</li>
    </ol>
</div>
<div class="col-md-12">
    <span style="font-size:30px;font-weight:strong;">Kartu Pengingat Anda!</span>
    <a href="/flashcard/add" class="btn btn-primary btn-sm pull-right">Buat Kartu Pengingat</a>
    <br/>
    <br/>
</div>
<div class="col-md-12">
    {% if flashcard %}
	    {% for card in flashcard %}
	    	<div class="flashcard col-md-3">
		    	<div class="panel panel-default">
		          <div class="panel-heading">
		            <h4 class="panel-title">{{ card.name }}</h4>
		          </div>
		          <div class="panel-body" style="word-wrap:break-word;">
		          	<ul class="list-group" id="flashcard-item-{{ card.id }}">
					{% for item in card.flashcarditem_set.all %}
		            <li class="list-group-item">{{ item.name }} <a data="{{ item.id }}" onclick="deleteFlashcardItem(this)" class="btn btn-xs btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span></a></li>
					{% endfor %}
					</ul>
				  </div>
		          <div class="panel-footer">
		            <div class="btn-group dropup">
					  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					    <span class="glyphicon glyphicon-wrench"></span>
					  </button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="/task_project/{{ project.id }}"><span class="glyphicon glyphicon-eye-open"></span> Detail</a>  </li>
			            <li><a href="/flashcard/edit/{{ card.id }}"><span class="glyphicon glyphicon-pencil"></span> Edit </a></li>
			            <li class="divider"></li>
					    <li><a href="/flashcard/delete/{{ card.id }}"><span class="glyphicon glyphicon-trash"></span> Hapus</a> </li>
					  </ul>
					</div>
					&nbsp;
					<a data-toggle="modal" href="#tambahFlashcardItem" onclick="addFlashcardItem('flashcard-item-{{ card.id }}', {{ card.id }});" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span></a>
		          </div>
		        </div>
	        </div>

	    {% endfor %}
    {% else %}
    <div style="text-align:center;font-size:20px;padding-top:20px;padding-bottom:30px;" class="well">
        Anda belum membuat flashcard satupun..
    </div>
    {% endif %}   

</div>

<!-- Modal -->
<div class="modal fade" id="tambahFlashcardItem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	      <h4 class="modal-title">Penambahan Item - </h4>
	    </div>
    	<form class="form-horizontal" id="form-add-flashcard-item">
            <div class="modal-body">
		        {% csrf_token %}
				<div class="form-group">
					<label for="flashcard-item-name" class="col-lg-2 control-label">Flashcard Item</label>
					<div class="col-lg-10">
					  <input class="form-control" id="flashcard-item-name" name="flashcard-item-name" placeholder="Isi dengan Flashcard Item..." type="text">
					  <input id="flashcard-item-target" type="hidden">
					  <input id="flashcard-item-flashcard" name="flashcard-item-flashcard" type="hidden" value="">
					</div>
				</div>
		    </div>
		    <div class="modal-footer">
		      <button type="button" class="btn btn-danger" data-dismiss="modal">Batalkan</button>
		      <button type="button" class="btn btn-primary" onclick="submitFlashcardItem();">Tambah</button>
		    </div>
	    </form>
	  </div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% load staticfiles %}
<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$('#container').masonry({
			itemSelector : '.flashcard',
		});
		
	});

	function addFlashcardItem(target, flashcard_id){
		console.log(target);
		
		$('#flashcard-item-target').val(target);
		$('#flashcard-item-flashcard').val(flashcard_id);
			
	}

	function submitFlashcardItem(){
		console.log($('#form-add-flashcard-item').serialize());
		csrftoken = $('input[name="csrfmiddlewaretoken"]').val();
        console.log("csrf token: "+csrftoken);

		$.ajax({
            url : "/api/flashcard/item/add/",
            type: "POST",
            data: $('#form-add-flashcard-item').serialize(),
            beforeSend: function(xhr, settings){
                console.log(settings);
                if (!csrfSafeMethod(settings.type)) {
                    // Send the token to same-origin, relative URLs only.
                    // Send the token only if the method warrants CSRF protection
                    // Using the CSRFToken value acquired earlier
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }

            },
            success : function(data){
                
                if (data.error == 200){
                	// console.log(JSON.parse(data.results));
                	results = JSON.parse(data.results);
                	console.log(results);

                	elem = "";
                	for (i in results){
                		elem += '<li class="list-group-item">'+results[i].fields.name+' <a data="'+results[i].pk+'" onclick="deleteFlashcardItem(this)" class="btn btn-xs btn-danger pull-right">'+
                				'<span class="glyphicon glyphicon-trash"></span></a> </li>';
                	}
                }
                else {
                    alert(data.msg);
                }
               	
               	$('#'+$('#flashcard-item-target').val()).html(elem);
				$('#'+$('#flashcard-item-target').val()).hide();
            },
            complete: function (xhr, status) {
        		$('#tambahFlashcardItem').modal('hide');	
        		
            	$('#'+$('#flashcard-item-target').val()).fadeIn();
				

        		$('#flashcard-item-name').val('');
				$('#flashcard-item-target').val('');
				$('#flashcard-item-flashcard').val('');
            	
			}
        });
	}

	function deleteFlashcardItem(elem){
		console.log(elem);
		csrftoken = $('input[name="csrfmiddlewaretoken"]').val();
        console.log("csrf token: "+csrftoken);
        
        $.ajax({
            url : "/api/flashcard/item/delete/",
            type: "POST",
            data: 'flashcard-item-id='+$(elem).attr('data'),
            beforeSend: function(xhr, settings){
                console.log(settings);
                if (!csrfSafeMethod(settings.type)) {
                    // Send the token to same-origin, relative URLs only.
                    // Send the token only if the method warrants CSRF protection
                    // Using the CSRFToken value acquired earlier
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }

            },
            success : function(data){
                
                if (data.error == 200){
                	$(elem).parent().fadeOut('slow', function(){ 
			    	 	$(elem).parent().remove();
			        });	
                }
                else {
                    alert(data.msg);
                }
            },
            complete: function (xhr, status) {
        		
			}
        });
    }
</script>

{% endblock %}