tofinish/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'tofinish.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^grappelli/', include('grappelli.urls')),
    url(r'^index/', 'main.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'test_template/$', 'main.views.test_template'),
    url(r'login/$', 'main.views.login_form'),
    url(r'login/process/$', 'main.views.login_process'),
    url(r'logout/', 'main.views.logout_view'),
    url(r'^profile/(\d+)/$', 'main.views.users_profile'),

    url(r'task_project/$', 'task_project.views.index'),
 	url(r'task_project/add$', 'task_project.views.add'),
 	url(r'^task_project/(\d+)', 'task_project.views.detail'),
 	url(r'^task_project/delete/(\d+)', 'task_project.views.delete'),   
 	url(r'^task_project/edit/(\d+)', 'task_project.views.edit'),   
 	url(r'^task_project/edit_process$', 'task_project.views.edit_process'),   
 	url(r'^task_project/member/(\d+)', 'task_project.views.list_member'),
 	url(r'^task_project/groups/(\d+)', 'task_project.views.list_task_groups'),
 	url(r'^task_project/tasks/(\d+)', 'task_project.views.list_tasks'),
 	url(r'^task_project/groups/edit/(\d+)/(\d+)', 'tasks.views.edit_group'),   
 	url(r'^task_project/groups/delete/(\d+)', 'tasks.views.delete_group'),   
 	url(r'^task_project/groups/edit_process$', 'tasks.views.edit_group_process'),   
 	url(r'^task_project/groups/add/(\d+)', 'tasks.views.add_group'),
 	url(r'^task_project/groups/detail/(\d+)', 'tasks.views.detail_group'),
 	url(r'^task_project/invitation/$', 'task_project.views.invitation'),
    url(r'^task_project/invitation/before/$', 'task_project.views.invitation_before'),
    url(r'^task_project/invitation/approve/(\d+)', 'task_project.views.approve_invitation'),
    
 	url(r'^tasks/add/(\d+)', 'tasks.views.add'),
 	url(r'^tasks/edit/(\d+)', 'tasks.views.edit'),
 	url(r'^tasks/edit_process', 'tasks.views.edit_process'),
 	url(r'^tasks/delete/(\d+)', 'tasks.views.delete'),   
 	url(r'^tasks/(\d+)', 'tasks.views.detail'),
 	url(r'^tasks/mine', 'tasks.views.my_task'),
 	url(r'^tasks/discussion/add', 'tasks.views.add_discussion_process'),
    url(r'^tasks/discussion/delete/(\d+)', 'tasks.views.delete_discussion'),
    url(r'^tasks/attachment/add', 'tasks.views.add_attachment_process'),
    
    url(r'^flashcard/$', 'flashcard.views.index'),
 	url(r'^flashcard/add$', 'flashcard.views.add'),
 	url(r'^flashcard/delete/(\d+)', 'flashcard.views.delete'), 
 	url(r'^flashcard/edit/(\d+)', 'flashcard.views.edit'),   
 	url(r'^flashcard/edit_process$', 'flashcard.views.edit_process'),  

 	url(r'^api/users/all$', 'main.views.all_users'),   
 	url(r'^api/task_project_member/add/(\d+)/(\d+)', 'task_project.views.add_member'),   
 	url(r'^api/task_project_member/by_project/(\d+)', 'task_project.views.get_member_by_project'),   
 	url(r'^api/task_project_member/suggest/(\d+)', 'task_project.views.suggest_member_by_project'),   
 	url(r'^api/task_project_member/reject/', 'task_project.views.reject_member'), 
    url(r'^api/task_project_member/leave/', 'task_project.views.leave_member'),
    url(r'^api/task_project_member/reapprove/', 'task_project.views.reapprove_member'),
    url(r'^api/tasks/task_project/(\d+)', 'tasks.views.all_tasks_by_project'),
    url(r'^api/tasks/change/', 'tasks.views.change_task_status'),
    url(r'^api/tasks/attachment/delete/', 'tasks.views.delete_attachment_process'),
    url(r'^api/tasks/discussion/delete/', 'tasks.views.delete_discussion_process'),
    url(r'^api/flashcard/item/add/', 'flashcard.views.add_item'),   
	url(r'^api/flashcard/item/delete/', 'flashcard.views.delete_item'),   
		 										
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models
from task_project.models import TaskProject, TaskProjectMember
from django.contrib.auth.models import User

# 2015-04-21 00:20:01.507595+00:00

class TaskGroup(models.Model):
	name = models.CharField(max_length=50, default="unknown")
	description = models.TextField(blank=True, default="fill your description")
	created_time = models.DateTimeField(auto_now=True)
	task_project = models.ForeignKey(TaskProject)
	owner = models.ForeignKey(User, default=1)

	def __unicode__(self):
		return self.name
    
	class Meta:
		ordering = ['name']

class Tasks(models.Model):
	FINISHED = 'FN'
	PLANNING = 'PL'
	REVIEWED = 'RV'
	PENDING = 'PD'
	FAILED = 'FL'
	ONGOING = 'OG'

	STATUS_CHOICES = (
		(FINISHED, 'Finished'),
		(PLANNING, 'Planning'),
		(REVIEWED, 'Reviewed'),
		(PENDING, 'Pending'),
		(FAILED, 'Failed'),
		(ONGOING, 'Ongoing')
			
	)
	
	name = models.CharField(max_length=50, default="unknown")
	description = models.TextField(blank=True, default="fill your description")
	created_time = models.DateTimeField(auto_now=True)
	task_group = models.ForeignKey(TaskGroup)
	owner = models.ForeignKey(User, default=1, related_name='owner')
	executor = models.ManyToManyField(User, default=(1,), related_name='executor')
	status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=PLANNING)
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()
	
	def __unicode__(self):
		return self.name
    
	class Meta:
		ordering = ['created_time']

class TaskAttachment(models.Model):
	TASK = 'TS'
	TASK_COMMENT = 'TC'

	SOURCE_CHOICES = (
		(TASK, 'Task'),
		(TASK_COMMENT, 'Task Comment'),
	)

	name = models.CharField(max_length=200, default="unknown")
	description = models.TextField(blank=True, default="fill your description")
	created_time = models.DateTimeField(auto_now=True)
	tasks = models.ForeignKey(Tasks)
	sender = models.ForeignKey(User, default=1)
	file_path = models.TextField(blank=True)
	source = models.CharField(max_length=2, choices=SOURCE_CHOICES, default=TASK)

	def __unicode__(self):
		return self.name
    
	class Meta:
		ordering = ['created_time']

class TaskDiscussion(models.Model):
	message = models.TextField(blank=True, default="fill your description")
	created_time = models.DateTimeField(auto_now=True)
	tasks = models.ForeignKey(Tasks)
	sender = models.ForeignKey(User, default=1)

	def __unicode__(self):
		return self.name
    
	class Meta:
		ordering = ['created_time']

tasks/views.py
from django.shortcuts import render_to_response, redirect
from django.http import HttpResponse, QueryDict
from django.core.context_processors import csrf
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.contrib.auth.models import User
from django.forms import ModelChoiceField

from task_project.models import *
from tasks.forms import *
from tasks.models import *
from tofinish.settings import MEDIA_ROOT

from datetime import datetime
from itertools import chain

import json
import os
import hashlib

# Create your views here.
login_url = '/login/'

@login_required(login_url=login_url)
def index(request):
	task_project = TaskProject.objects.all().filter(owner=request.user.id)
	return render_to_response('task_project/list.html', { 'task_project':task_project })

@login_required(login_url=login_url)
def add(request, group_id):
	task_group = TaskGroup.objects.get(id=int(group_id))
	if request.method == 'POST':
		form = TasksForm(request.POST)
		
		form.fields['task_group'] = forms.ModelChoiceField(TaskGroup.objects.all().filter(task_project=task_group.task_project), widget=forms.Select(attrs={'class':'form-control'}))
		
		project_member = TaskProjectMember.objects.all().filter(task_project=task_group.task_project)
		users_list = []
		for member in project_member:
			users_list.append(member.member.id)
		users_list = tuple(users_list)
		form.fields['executor'] = forms.ModelMultipleChoiceField(User.objects.all().filter(id__in=users_list), widget=forms.SelectMultiple(attrs={'class':'form-control'}))

		if form.is_valid():
			user = User.objects.get(id=int(request.POST['owner']))	
			executor_list = tuple(request.POST.getlist('executor'))

			tasks = Tasks.objects.create(
				name = request.POST['name'],
				description = request.POST['description'],
				owner = user,
				task_group = task_group,
				status = request.POST['status'],
				start_time = request.POST['start_time'],
				end_time = request.POST['end_time']
			)
			
			for person in executor_list:
				tasks.executor.add(person)

			tasks.save()

			return redirect(
				'/task_project/groups/detail/' + request.POST['task_group']
			)
	else:
		
		form = TasksForm(initial={ 'owner':request.user.id, 'task_group':task_group.id })
		form.fields['task_group'] = forms.ModelChoiceField(TaskGroup.objects.all().filter(task_project=task_group.task_project), widget=forms.Select(attrs={'class':'form-control'}))
		
		project_member = TaskProjectMember.objects.all().filter(task_project=task_group.task_project)
		users_list = []
		for member in project_member:
			users_list.append(member.member.id)
		users_list = tuple(users_list)
		form.fields['executor'] = forms.ModelMultipleChoiceField(User.objects.all().filter(id__in=users_list), widget=forms.SelectMultiple(attrs={'class':'form-control'}))
		

	c = {}
	c.update(csrf(request))
	c.update({ 'form':form, 'task_group':task_group })
	return render_to_response('tasks/add.html', c)

@login_required(login_url=login_url)
def delete(request, tasks_id):
	tasks = Tasks.objects.get(id=int(tasks_id))
	task_group_id = tasks.task_group.id
	tasks.delete()
	return redirect('/task_project/groups/detail/'+str(task_group_id))	

@login_required(login_url=login_url)
def edit(request, tasks_id):
	tasks = Tasks.objects.get(id=int(tasks_id))
	
	form = TasksForm(initial={ 
		'owner':request.user.id, 
		'task_group':tasks.task_group.id, 
		'name': tasks.name,
		'description': tasks.description,
		'status': tasks.status,
		'start_time': tasks.start_time,
		'end_time': tasks.end_time
	})

	form.fields['task_group'] = forms.ModelChoiceField(TaskGroup.objects.all().filter(task_project=tasks.task_group.task_project), widget=forms.Select(attrs={'class':'form-control'}))
	
	project_member = TaskProjectMember.objects.all().filter(task_project=tasks.task_group.task_project, status='APV')
	users_list = []
	for member in project_member:
		users_list.append(member.member.id)

	users_chosen = {}
	for member in tasks.executor.all():
		users_chosen[member.id] = True
		
	users_list = tuple(users_list)
	form.fields['executor'] = forms.ModelMultipleChoiceField(User.objects.all().filter(id__in=users_list), widget=forms.SelectMultiple(attrs={'class':'form-control'}))
	form.fields['executor'].initial = users_chosen


	c = {}
	c.update(csrf(request))
	c.update({'form':form, 'task_group':tasks.task_group, 'tasks':tasks })
	return render_to_response('tasks/edit.html', c)

@login_required(login_url=login_url)
def edit_process(request):
	if request.method == 'POST':
		form = TasksForm(request.POST)
		task_group = TaskGroup.objects.get(id=int(request.POST['task_group']))

		form.fields['task_group'] = forms.ModelChoiceField(TaskGroup.objects.all().filter(task_project=task_group.task_project), widget=forms.Select(attrs={'class':'form-control'}))
		project_member = TaskProjectMember.objects.all().filter(task_project=task_group.task_project)
		users_list = []
		for member in project_member:
			users_list.append(member.member.id)
		users_list = tuple(users_list)
		form.fields['executor'] = forms.ModelMultipleChoiceField(User.objects.all().filter(id__in=users_list), widget=forms.SelectMultiple(attrs={'class':'form-control'}))

		if form.is_valid():
			user = User.objects.get(id=int(request.POST['owner']))
			executor_list = tuple(request.POST.getlist('executor'))
			tasks = Tasks.objects.get(id=int(request.POST['tasks_id']))
			
			tasks.name = request.POST['name']
			tasks.description = request.POST['description']
			tasks.owner = user
			tasks.task_group = task_group
			tasks.status = request.POST['status']
			tasks.start_time = request.POST['start_time']
			tasks.end_time = request.POST['end_time']
			tasks.executor = User.objects.all().filter(id__in=executor_list)

			tasks.save()

			return redirect(
				'/task_project/groups/detail/' + request.POST['task_group']
			)
		else:
			return redirect('/tasks/edit/'+request.POST['tasks_id'])

@login_required(login_url=login_url)
def detail(request, tasks_id):
	task = Tasks.objects.get(id=int(tasks_id))
	discussion_form = TaskDiscussionForm(initial={'sender':request.user.id, 'task':task.id})
	attachment_form = TaskAttachmentForm(initial={'task':tasks_id, 'source':'TS'})
	comment_attachment_form = TaskAttachmentForm(initial={'task':tasks_id, 'source':'TC'})
	temp_list_discussion = TaskDiscussion.objects.all().filter(tasks=task)
	temp_list_attachment = TaskAttachment.objects.filter(tasks=tasks_id, source='TC')
	list_attachment = TaskAttachment.objects.filter(tasks=tasks_id, source='TS')

	list_discussion = sorted(
						chain(temp_list_discussion, temp_list_attachment), 
						key = lambda instance: instance.created_time)

	for i in range(0, len(list_attachment)):
		start_idx = list_attachment[i].name.find('---')
		end_idx = list_attachment[i].name.rfind('.')
		hash_str = list_attachment[i].name[start_idx:end_idx]
		file_name = list_attachment[i].name.replace(hash_str, '')
		list_attachment[i].file_name = file_name

	tasks_status = dict(Tasks.STATUS_CHOICES)
	
	c = {}
	c.update(csrf(request))
	c.update({ 
				'discussion_form':discussion_form, 
				'attachment_form':attachment_form, 
				'comment_attachment_form':comment_attachment_form, 
				'task':task, 
				'list_discussion':list_discussion,
				'list_attachment': list_attachment,
				'user_id':request.user.id, 
				'tasks_status':tasks_status 
			})

	return render_to_response('tasks/detail.html', c)

@login_required(login_url=login_url)
def add_group(request, project_id):
	task_project = TaskProject.objects.get(id=int(project_id))
	if request.method == 'POST':
		form = TaskGroupForm(request.POST)
		if form.is_valid():
			user = User.objects.get(id=int(request.POST['owner']))
			task_project = TaskProject.objects.get(id=int(request.POST['task_project']))	
			task_group = TaskGroup(
				name = request.POST['name'],
				description = request.POST['description'],
				owner = user,
				task_project = task_project,
			)
			task_group.save()

			return redirect(
				'/task_project/groups/' + request.POST['task_project']
			)
	else:
		task_project = TaskProject.objects.get(id=int(project_id))
		form = TaskGroupForm(initial={ 'owner':request.user.id, 'task_project':task_project.id })
		form.fields['task_project'] = forms.ModelChoiceField(TaskProject.objects.all().filter(owner=request.user.id), widget=forms.Select(attrs={'class':'form-control'}))
	
	c = {}
	c.update(csrf(request))
	c.update({ 'form':form, 'task_project':task_project })
	return render_to_response('tasks/add_group.html', c)

@login_required(login_url=login_url)
def edit_group(request, group_id, project_id):
	task_project = TaskProject.objects.get(id=int(project_id))
	task_group = TaskGroup.objects.get(id=int(group_id))
	form = TaskGroupForm(
		initial= { 
			'name' : task_group.name,
			'description' : task_group.description,
			'task_project' : task_group.task_project,
			'owner':task_group.owner.id 
		}
	)
	c = {}
	c.update(csrf(request))
	c.update({'form':form, 'task_project':task_project, 'task_group':task_group })
	return render_to_response('tasks/edit_group.html', c)

@login_required(login_url=login_url)
def edit_group_process(request):
	if request.method == 'POST':
		form = TaskGroupForm(request.POST)
		if form.is_valid():
			user = User.objects.get(id=int(request.POST['owner']))
			project = TaskProject.objects.get(id=int(request.POST['task_project']))
			task_group = TaskGroup.objects.get(id=int(request.POST['task_group_id']))
			task_group.name = request.POST['name']
			task_group.description = request.POST['description']
			task_group.owner = user
			task_group.task_project = project
			task_group.save()
			return redirect('/task_project/groups/'+request.POST['task_project'])
		else:
			return redirect('/task_project/groups/edit/'+request.POST['task_project'])

@login_required(login_url=login_url)
def delete_group(request, task_group_id):
	task_group = TaskGroup.objects.get(id=int(task_group_id))

templates/tasks/add.html
{% extends "main/layout.html" %}

{% block main_content %}
<div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/task_project">Daftar Proyek</a></li>
      <li><a href="/task_project/{{ task_group.task_project.id  }}">Detail</a></li>
      <li><a href="/task_project/groups/{{ task_group.task_project.id }}">Task Group</a></li>
      <li><a href="/task_project/groups/detail/{{ task_group.id }}">Detail Task Group</a></li>
      <li class="active">Tambah Tasks</li>
    </ol>
</div>
<div class="col-md-12">
    <span style="font-size:30px;font-weight:strong;">Tambah Tasks</span>
    <br/>
    <br/>
</div>
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
          <form class="form-horizontal"action="/tasks/add/{{ task_group.id }}" method="post">
                {% csrf_token %}
                  <div class="form-group">
                    <label for="inputEmail1" class="col-lg-2 control-label">Nama</label>
                    <div class="col-lg-10">
                      <!-- <input class="form-control" id="inputEmail1" placeholder="Email" type="email"> -->
                        {{ form.name.errors }}
                        {{ form.name }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Deskripsi</label>
                    <div class="col-lg-10">
                      <!-- <input class="form-control" id="inputPassword1" placeholder="Password" type="password"> -->
                      {{ form.description.errors }}
                      {{ form.description }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Status</label>
                    <div class="col-lg-10">
                      {{ form.status.errors }}
                      {{ form.status }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Eksekutor</label>
                    <div class="col-lg-10">
                      {{ form.executor.errors }}
                      {{ form.executor }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Task Group</label>
                    <div class="col-lg-10">
                        {{ form.task_group.errors }}
                        {{ form.task_group }}
                        {{ form.owner.errors }}
                        {{ form.owner }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Mulai Tugas</label>
                    <div class="col-lg-10">
                      {{ form.start_time.errors }}
                      {{ form.start_time }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Akhir Tugas</label>
                    <div class="col-lg-10">
                      {{ form.end_time.errors }}
                      {{ form.end_time }}
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                      <input type="submit" class="btn btn-info" value="Simpan" />
                    </div>
                  </div>
            </form>
      </div>
    </div>
</div>

{% load staticfiles %}

<link href="{% static 'js/jquery-ui-1.10.4/themes/base/minified/jquery-ui.min.css' %}" rel="stylesheet">
<link href="{% static 'js/jquery-timepicker/jquery-ui-timepicker-addon.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4/ui/minified/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery-timepicker/jquery-ui-timepicker-addon.min.js' %}"></script>

<script type="text/javascript">
    $( "#id_start_time" ).datetimepicker({
      dateFormat: 'yy-mm-dd',
      timeFormat: 'HH:mm'
    });
    
    $( "#id_end_time" ).datetimepicker({
      dateFormat: 'yy-mm-dd',
      timeFormat: 'HH:mm'
    });
</script>


{% endblock %}

templates/tasks/edit.html
{% extends "main/layout.html" %}

{% block main_content %}
<div class="col-md-12">
    <ol class="breadcrumb">
      <li><a href="/task_project">Daftar Proyek</a></li>
      <li><a href="/task_project/{{ task_group.task_project.id  }}">Detail</a></li>
      <li><a href="/task_project/groups/{{ task_group.task_project.id }}">Task Group</a></li>
      <li><a href="/task_project/groups/detail/{{ task_group.id }}">Detail Task Group</a></li>
      <li class="active">Edit Tasks</li>
    </ol>
</div>
<div class="col-md-12">
    <span style="font-size:30px;font-weight:strong;">Edit Tasks</span>
    <br/>
    <br/>
</div>
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
          <form class="form-horizontal"action="/tasks/edit_process" method="post">
                {% csrf_token %}
                  <div class="form-group">
                    <label for="inputEmail1" class="col-lg-2 control-label">Nama</label>
                    <div class="col-lg-10">
                      <!-- <input class="form-control" id="inputEmail1" placeholder="Email" type="email"> -->
                        {{ form.name.errors }}
                        {{ form.name }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Deskripsi</label>
                    <div class="col-lg-10">
                      <!-- <input class="form-control" id="inputPassword1" placeholder="Password" type="password"> -->
                      {{ form.description.errors }}
                      {{ form.description }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Status</label>
                    <div class="col-lg-10">
                      {{ form.status.errors }}
                      {{ form.status }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Eksekutor</label>
                    <div class="col-lg-10">
                      {{ form.executor.errors }}
                      {{ form.executor }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Task Group</label>
                    <div class="col-lg-10">
                        {{ form.task_group.errors }}
                        {{ form.task_group }}
                        {{ form.owner.errors }}
                        {{ form.owner }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Mulai Tugas</label>
                    <div class="col-lg-10">
                      {{ form.start_time.errors }}
                      {{ form.start_time }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword1" class="col-lg-2 control-label">Akhir Tugas</label>
                    <div class="col-lg-10">
                      {{ form.end_time.errors }}
                      {{ form.end_time }}
                      <input type="hidden" name="tasks_id" value="{{ tasks.id }}" />
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                      <input type="submit" class="btn btn-info" value="Simpan" />
                    </div>
                  </div>
            </form>
      </div>
    </div>

  <!-- 
    <form action="/task_project/add" method="post">
    	{% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Submit" />
    </form> -->
</div>

{% load staticfiles %}

<link href="{% static 'js/jquery-ui-1.10.4/themes/base/minified/jquery-ui.min.css' %}" rel="stylesheet">
<link href="{% static 'js/jquery-timepicker/jquery-ui-timepicker-addon.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4/ui/minified/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery-timepicker/jquery-ui-timepicker-addon.min.js' %}"></script>

<script type="text/javascript">
    $( "#id_start_time" ).datetimepicker({
      dateFormat: 'yy-mm-dd',
      timeFormat: 'HH:mm'
    });
    
    $( "#id_end_time" ).datetimepicker({
      dateFormat: 'yy-mm-dd',
      timeFormat: 'HH:mm'
    });
</script>

{% endblock %}

templates/tasks/my_task.html
{% extends "main/layout.html" %}

{% block main_content %}
<div class="col-md-12">
    <ol class="breadcrumb">
      <li class="active">Daftar Tugas</li>
    </ol>
</div>
<div class="col-md-12">
    <span style="font-size:30px;font-weight:strong;">Tugas Anda!!!</span>
    <!-- <a href="/task_project/add" class="btn btn-primary btn-sm pull-right">Buat Proyek Baru</a> -->
    <br/>
    <br/>
</div>
<div class="col-md-12">
    {% if tasks %}
    <table  class="table table-striped">
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.name }}</td>
                <td>{{ task.task_group.name }} <br/> ( {{ task.task_group.task_project.name }} )</td>
                <td>Ditugaskan oleh {{ task.owner }} <br/> dikerjakan dari {{ task.start_time }} hingga {{ task.end_time }}</td>
                <td>{{ task.get_status_display }}</td>
                <td style="text-align:center;">
                    <!-- <a class="btn btn-primary btn-xs" href="/task_project/member/{{ task.task_group.task_project.id }}"><span class="glyphicon glyphicon-user"></span></a> --> 
                    <a class="btn btn-info btn-xs" href="/tasks/{{ task.id }}"><span class="glyphicon glyphicon-eye-open"></span></a> 
                    <!-- <a class="btn btn-success btn-xs" href="/task_project/edit/{{ project.id }}"><span class="glyphicon glyphicon-pencil"></span></a>   -->
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div style="text-align:center;font-size:20px;padding-top:20px;padding-bottom:30px;" class="well">
        Anda belum diajak siapapun untuk ikut proyek..
    </div>
    {% endif %}  
</div>
{% endblock %}